-- falta atualizar

USE SENACPROJETO;

USE SenacProjeto;

INSERT INTO `department` (`Name`) VALUES
                                      ('Software Engineer'),
                                      ('Data Scientist'),
                                      ('Network Administrator'),
                                      ('System Analyst'),
                                      ('Cybersecurity Specialist');

INSERT INTO `seller` (`Name`, `Email`, `BirthDate`, `BaseSalary`, `DepartmentId`) VALUES
                                                                                      ('Emily Davis', 'emily.davis@example.com', '1985-01-01', 4500.50, 1),
                                                                                      ('Michael Brown', 'michael.brown@example.com', '1992-02-14', 5200.00, 2),
                                                                                      ('Joshua Harris', 'joshua.harris@example.com', '1988-03-23', 6100.00, 3),
                                                                                      ('Sophia White', 'sophia.white@example.com', '1995-04-18', 4800.25, 4),
                                                                                      ('James Martin', 'james.martin@example.com', '1990-05-10', 5700.75, 5),
                                                                                      ('Olivia Thompson', 'olivia.thompson@example.com', '1992-06-21', 4950.00, 1),
                                                                                      ('Benjamin Garcia', 'benjamin.garcia@example.com', '1986-07-30', 6300.00, 2),
                                                                                      ('Ava Martinez', 'ava.martinez@example.com', '1993-08-17', 5200.00, 3),
                                                                                      ('Lucas Rodriguez', 'lucas.rodriguez@example.com', '1987-09-25', 5800.00, 4),
                                                                                      ('Mia Hernandez', 'mia.hernandez@example.com', '1991-10-05', 4600.00, 5),
                                                                                      ('Alexander Lee', 'alexander.lee@example.com', '1989-11-12', 5900.00, 1),
                                                                                      ('Isabella Wilson', 'isabella.wilson@example.com', '1994-12-08', 5100.00, 2),
                                                                                      ('Matthew Walker', 'matthew.walker@example.com', '1985-01-19', 5600.00, 3),
                                                                                      ('Charlotte King', 'charlotte.king@example.com', '1990-02-25', 4700.00, 4),
                                                                                      ('Daniel Wright', 'daniel.wright@example.com', '1987-03-14', 6200.00, 5),
                                                                                      ('Amelia Scott', 'amelia.scott@example.com', '1993-04-20', 4800.00, 1),
                                                                                      ('Henry Young', 'henry.young@example.com', '1991-05-09', 5400.00, 2),
                                                                                      ('Harper Green', 'harper.green@example.com', '1995-06-30', 5000.00, 3),
                                                                                      ('Sebastian Adams', 'sebastian.adams@example.com', '1989-07-15', 6100.00, 4),
                                                                                      ('Evelyn Nelson', 'evelyn.nelson@example.com', '1992-08-22', 4700.00, 5),
                                                                                      ('Elijah Carter', 'elijah.carter@example.com', '1986-09-11', 5800.00, 1),
                                                                                      ('Abigail Mitchell', 'abigail.mitchell@example.com', '1990-10-03', 5300.00, 2),
                                                                                      ('Logan Perez', 'logan.perez@example.com', '1993-11-18', 5900.00, 3),
                                                                                      ('Emily Turner', 'emily.turner@example.com', '1987-12-25', 6200.00, 4),
                                                                                      ('Mason Collins', 'mason.collins@example.com', '1991-01-06', 4800.00, 5),
                                                                                      ('Lily Edwards', 'lily.edwards@example.com', '1994-02-14', 5700.00, 1),
                                                                                      ('Jackson Ramirez', 'jackson.ramirez@example.com', '1985-03-20', 5200.00, 2),
                                                                                      ('Sofia Bell', 'sofia.bell@example.com', '1992-04-07', 6100.00, 3),
                                                                                      ('Aiden Ward', 'aiden.ward@example.com', '1993-05-30', 5000.00, 4),
                                                                                      ('Hannah Cox', 'hannah.cox@example.com', '1988-06-12', 5500.00, 5),
                                                                                      ('Jack Wood', 'jack.wood@example.com', '1991-07-21', 5800.00, 1),
                                                                                      ('Chloe Brooks', 'chloe.brooks@example.com', '1990-08-10', 4700.00, 2),
                                                                                      ('Grayson Murphy', 'grayson.murphy@example.com', '1989-09-15', 6000.00, 3),
                                                                                      ('Zoe Bailey', 'zoe.bailey@example.com', '1995-10-05', 4900.00, 4),
                                                                                      ('Ethan Rivera', 'ethan.rivera@example.com', '1986-11-22', 5300.00, 5),
                                                                                      ('Scarlett Cooper', 'scarlett.cooper@example.com', '1994-12-02', 5100.00, 1),
                                                                                      ('Caleb Richardson', 'caleb.richardson@example.com', '1988-01-14', 5700.00, 2),
                                                                                      ('Aubrey Roberts', 'aubrey.roberts@example.com', '1991-02-26', 4800.00, 3),
                                                                                      ('Lucas Cook', 'lucas.cook@example.com', '1985-03-17', 6000.00, 4),
                                                                                      ('Riley Morgan', 'riley.morgan@example.com', '1990-04-11', 5000.00, 5),
                                                                                      ('Jackson Peterson', 'jackson.peterson@example.com', '1987-05-05', 6200.00, 1),
                                                                                      ('Victoria Reed', 'victoria.reed@example.com', '1993-06-27', 4900.00, 2),
                                                                                      ('Joseph Kelly', 'joseph.kelly@example.com', '1989-07-12', 5500.00, 3),
                                                                                      ('Ella Foster', 'ella.foster@example.com', '1992-08-23', 4800.00, 4),
                                                                                      ('David Howard', 'david.howard@example.com', '1986-09-07', 6100.00, 5),
                                                                                      ('Layla Flores', 'layla.flores@example.com', '1995-10-19', 4700.00, 1),
                                                                                      ('James Bennett', 'james.bennett@example.com', '1988-11-30', 6000.00, 2),
                                                                                      ('Ava Sanders', 'ava.sanders@example.com', '1994-12-15', 4900.00, 3);